name: .NET Framework Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Harus Windows untuk .NET Framework

    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 3. Setup NuGet (untuk restore dependencies)
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # 4. Restore dependencies
      - name: Restore NuGet packages
        run: nuget restore enkripauser.sln

      # 5. Build solusi dengan MSBuild
      - name: Build solution
        run: msbuild enkripauser.sln /p:Configuration=Release /p:Platform="Any CPU"
